# Generated by Django 2.2.10 on 2020-03-01 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aika',
            fields=[
                ('vvvvkkpp', models.IntegerField(primary_key=True, serialize=False)),
                ('pvm', models.DateField()),
                ('vuosi', models.IntegerField(verbose_name='Vuosi')),
                ('kk', models.IntegerField()),
                ('kk_nimi', models.CharField(max_length=20)),
                ('paiva', models.IntegerField()),
                ('vko', models.IntegerField()),
                ('viikonpaiva', models.IntegerField()),
                ('viikonpaiva_lyh', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Aika',
            },
        ),
        migrations.CreateModel(
            name='Harjoitus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvm', models.DateField(verbose_name='Päivä')),
                ('kesto', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('kesto_h', models.PositiveIntegerField(blank=True, null=True, verbose_name='h')),
                ('kesto_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='min')),
                ('matka', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vauhti_km_h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Vauhti (km/h)')),
                ('vauhti_min_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Vauhti (min/km)')),
                ('vauhti_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='min')),
                ('vauhti_s', models.PositiveIntegerField(blank=True, null=True, verbose_name='s')),
                ('keskisyke', models.IntegerField(blank=True, null=True)),
                ('kalorit', models.IntegerField(blank=True, null=True)),
                ('tuntuma', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('kommentti', models.TextField(blank=True, max_length=250, null=True)),
                ('vuorokaudenaika', models.IntegerField(choices=[(1, 'aamu'), (2, 'ilta')], default=2, verbose_name='')),
                ('nousu', models.IntegerField(blank=True, null=True, verbose_name='Nousu (m)')),
                ('aika', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='treenipaivakirja.Aika', verbose_name='vvvvkkpp')),
            ],
            options={
                'verbose_name_plural': 'Harjoitus',
            },
        ),
        migrations.CreateModel(
            name='Tehoalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jarj_nro', models.IntegerField(verbose_name='Järj.Nro')),
                ('tehoalue', models.CharField(max_length=100, verbose_name='Tehoalue')),
                ('alaraja', models.IntegerField(blank=True, null=True, verbose_name='Alaraja')),
                ('ylaraja', models.IntegerField(blank=True, null=True, verbose_name='Yläraja')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tehoalue',
                'ordering': ['jarj_nro'],
            },
        ),
        migrations.CreateModel(
            name='Teho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField()),
                ('kesto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kesto_h', models.PositiveIntegerField(blank=True, null=True, verbose_name='h')),
                ('kesto_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='min')),
                ('keskisyke', models.IntegerField(blank=True, null=True)),
                ('maksimisyke', models.IntegerField(blank=True, null=True, verbose_name='Maksimisyke')),
                ('matka', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vauhti_km_h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Vauhti (km/h)')),
                ('vauhti_min_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Vauhti (min/km)')),
                ('vauhti_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='min')),
                ('vauhti_s', models.PositiveIntegerField(blank=True, null=True, verbose_name='s')),
                ('harjoitus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treenipaivakirja.Harjoitus')),
                ('tehoalue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treenipaivakirja.Tehoalue')),
            ],
            options={
                'verbose_name_plural': 'Teho',
            },
        ),
        migrations.CreateModel(
            name='Laji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laji', models.CharField(max_length=10, verbose_name='Lyhenne')),
                ('laji_nimi', models.CharField(max_length=50, verbose_name='Laji')),
                ('laji_ryhma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lajiryhmä')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Laji',
                'ordering': ['laji_nimi'],
            },
        ),
        migrations.CreateModel(
            name='Kausi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kausi', models.CharField(max_length=20, verbose_name='Harjoituskausi')),
                ('alkupvm', models.DateField(verbose_name='Alkupäivä')),
                ('loppupvm', models.DateField(verbose_name='Loppupäivä')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kausi',
                'ordering': ['kausi'],
            },
        ),
        migrations.AddField(
            model_name='harjoitus',
            name='laji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treenipaivakirja.Laji', verbose_name='Laji'),
        ),
        migrations.AddField(
            model_name='harjoitus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
