# Generated by Django 2.2.10 on 2020-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treenipaivakirja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harjoitus',
            name='vuorokaudenaika',
            field=models.IntegerField(choices=[(1, 'aamupäivä'), (2, 'iltapäivä')], default=2, verbose_name=''),
        ),
    ]
