# Generated by Django 2.2.4 on 2019-11-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treenipaivakirja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harjoitus',
            old_name='pvm_fk',
            new_name='aika',
        ),
        migrations.RenameField(
            model_name='harjoitus',
            old_name='laji_fk',
            new_name='laji',
        ),
        migrations.RenameField(
            model_name='tehot',
            old_name='harjoitus_fk',
            new_name='harjoitus',
        ),
    ]
