# Generated by Django 2.2.10 on 2020-08-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treenipaivakirja', '0002_auto_20200410_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarUser',
            fields=[
                ('polar_user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('access_token', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True))),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('latest_exercise_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('latest_activity_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
