# Generated by Django 2.2.4 on 2019-11-23 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treenipaivakirja', '0003_kausi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tehot',
            new_name='teho',
        ),
        migrations.AlterModelOptions(
            name='teho',
            options={'verbose_name_plural': 'Teho'},
        ),
        migrations.RenameField(
            model_name='teho',
            old_name='teho',
            new_name='tehoalue',
        ),
        migrations.AddField(
            model_name='tehoalue',
            name='tehoalue',
            field=models.CharField(max_length=100, null=True, verbose_name='Tehoalue'),
        ),
        migrations.AlterField(
            model_name='kausi',
            name='kausi',
            field=models.CharField(max_length=20, verbose_name='Harjoituskausi'),
        ),
        migrations.AlterUniqueTogether(
            name='tehoalue',
            unique_together={('tehoalue', 'user')},
        ),
        migrations.RemoveField(
            model_name='tehoalue',
            name='teho',
        ),
    ]
