# Generated by Django 2.2.4 on 2019-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treenipaivakirja', '0004_auto_20191123_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehoalue',
            name='tehoalue',
            field=models.CharField(default='PK', max_length=100, verbose_name='Tehoalue'),
            preserve_default=False,
        ),
    ]
