# Generated by Django 2.2.10 on 2020-02-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treenipaivakirja', '0006_auto_20191208_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kausi',
            options={'ordering': ['kausi'], 'verbose_name_plural': 'Kausi'},
        ),
        migrations.AlterModelOptions(
            name='laji',
            options={'ordering': ['laji_nimi'], 'verbose_name_plural': 'Laji'},
        ),
        migrations.AlterModelOptions(
            name='tehoalue',
            options={'ordering': ['jarj_nro'], 'verbose_name_plural': 'Tehoalue'},
        ),
        migrations.AlterField(
            model_name='harjoitus',
            name='aika',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='treenipaivakirja.Aika', verbose_name='vvvvkkpp'),
        ),
        migrations.AlterField(
            model_name='harjoitus',
            name='laji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treenipaivakirja.Laji', verbose_name='Laji'),
        ),
        migrations.AlterField(
            model_name='teho',
            name='harjoitus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treenipaivakirja.Harjoitus'),
        ),
        migrations.AlterField(
            model_name='teho',
            name='maksimisyke',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maksimisyke'),
        ),
        migrations.AlterField(
            model_name='teho',
            name='tehoalue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='treenipaivakirja.Tehoalue'),
            preserve_default=False,
        ),
    ]
